<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="sv" xml:lang="sv"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Skriv ditt namn här">

<title>Statistiska test</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Lab3_student_rapport_files/libs/clipboard/clipboard.min.js"></script>
<script src="Lab3_student_rapport_files/libs/quarto-html/quarto.js"></script>
<script src="Lab3_student_rapport_files/libs/quarto-html/popper.min.js"></script>
<script src="Lab3_student_rapport_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Lab3_student_rapport_files/libs/quarto-html/anchor.min.js"></script>
<link href="Lab3_student_rapport_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Lab3_student_rapport_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Lab3_student_rapport_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Lab3_student_rapport_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Lab3_student_rapport_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Innehållsförteckning</h2>
   
  <ul>
  <li><a href="#förberedelseuppgifter" id="toc-förberedelseuppgifter" class="nav-link active" data-scroll-target="#förberedelseuppgifter">Förberedelseuppgifter</a></li>
  <li><a href="#grundläggande-begrepp-vid-hypotestestning" id="toc-grundläggande-begrepp-vid-hypotestestning" class="nav-link" data-scroll-target="#grundläggande-begrepp-vid-hypotestestning"><span class="header-section-number">1</span> Grundläggande begrepp vid hypotestestning</a></li>
  <li><a href="#testets-styrka-och-styrkefunktion" id="toc-testets-styrka-och-styrkefunktion" class="nav-link" data-scroll-target="#testets-styrka-och-styrkefunktion"><span class="header-section-number">2</span> Testets styrka och styrkefunktion</a>
  <ul class="collapse">
  <li><a href="#svar-till-exemplet-med-muntorrhet" id="toc-svar-till-exemplet-med-muntorrhet" class="nav-link" data-scroll-target="#svar-till-exemplet-med-muntorrhet">Svar till exemplet med muntorrhet</a></li>
  <li><a href="#några-statistiska-test-med-stickprov" id="toc-några-statistiska-test-med-stickprov" class="nav-link" data-scroll-target="#några-statistiska-test-med-stickprov">Några statistiska test med stickprov</a></li>
  </ul></li>
  <li><a href="#test-av-väntevärde-i-en-population-t-test" id="toc-test-av-väntevärde-i-en-population-t-test" class="nav-link" data-scroll-target="#test-av-väntevärde-i-en-population-t-test"><span class="header-section-number">3</span> Test av väntevärde i en population (t-test)</a></li>
  <li><a href="#jämförelse-av-väntevärden-i-två-populationer-t-test-vid-två-oberoende-stickprov" id="toc-jämförelse-av-väntevärden-i-två-populationer-t-test-vid-två-oberoende-stickprov" class="nav-link" data-scroll-target="#jämförelse-av-väntevärden-i-två-populationer-t-test-vid-två-oberoende-stickprov"><span class="header-section-number">4</span> Jämförelse av väntevärden i två populationer (t-test vid två oberoende stickprov)</a></li>
  <li><a href="#test-vid-matchade-data-stickprov-i-par" id="toc-test-vid-matchade-data-stickprov-i-par" class="nav-link" data-scroll-target="#test-vid-matchade-data-stickprov-i-par"><span class="header-section-number">5</span> Test vid matchade data (stickprov i par)</a>
  <ul class="collapse">
  <li><a href="#svar-till-några-av-denna-sektions-frågor" id="toc-svar-till-några-av-denna-sektions-frågor" class="nav-link" data-scroll-target="#svar-till-några-av-denna-sektions-frågor">Svar till några av denna sektions frågor:</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Andra format</h2><ul><li><a href="Lab3_student_rapport.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li><li><a href="Lab3_student_rapport.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Statistiska test</h1>
<p class="subtitle lead">Datorlaboration 3</p>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Författare</div>
  <div class="quarto-title-meta-heading">Tillhörighet</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Skriv ditt namn här </p>
  </div>
    <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Lunds Universitet
          </p>
      </div>
    </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Publicerad</div>
    <div class="quarto-title-meta-contents">
      <p class="date">14 mars 2024</p>
    </div>
  </div>
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="abstract-title">Abstrakt</div>
    <p>Syftet med dagens laboration är att du ska</p>
    <ul>
    <li>träna på de grundläggande begreppen inom hypotesprövning (t.ex. signifikansnivå och styrka) samt vilka slutsatser man kan dra från analysen</li>
    <li>bekanta dig med lite av de funktioner som finns i R vad det gäller olika grundläggande statistiska test</li>
    <li>arbeta med kursens Miniprojekt II.</li>
    </ul>
  </div>
</div>

</header>

<section id="förberedelseuppgifter" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="förberedelseuppgifter">Förberedelseuppgifter</h2>
<blockquote class="blockquote">
<p>Repetera begreppen <em>hypoteser, signifikansnivå, styrkefunktion</em> samt <em>modell med matchade data och modell med två oberoende stickprov</em>.</p>
<p>Du skall ha gjort följande uppgifter <em>innan</em> du kommer till laborationen.</p>
</blockquote>
<div class="callout callout-style-default callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hemuppgift 1
</div>
</div>
<div class="callout-body-container callout-body">
<p>För att träna på de grundläggande begreppen i hypotest gör uppgifterna <strong>Dig:4.4.1(felrisker)_3, _4 och _5 på övning 7</strong>.</p>
</div>
</div>
<div class="callout callout-style-default callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Hemuppgift 2
</div>
</div>
<div class="callout-body-container callout-body">
<p>För att träna på olika modeller gör <strong>Dig:5.2_1 och _2</strong>.</p>
</div>
</div>
<div class="callout callout-style-default callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Innan du sätter igång
</div>
</div>
<div class="callout-body-container callout-body">
<p>Ladda in R-funktioner som behövs för laborationen. Dessa funktioner kommer från R-paketet Räkna med variation, men för att undvika problem med installation har vi plockat ut de ni använder och sparat i en fil. Du “berättar” för R att dessa funktioner finns genom att köra följande kod:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"kod/funktioner_raknamedvariation_light.R"</span>)</span></code><button title="Kopiera till Urklipp" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</section>
<section id="grundläggande-begrepp-vid-hypotestestning" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Grundläggande begrepp vid hypotestestning</h1>
<blockquote class="blockquote">
<p>Läkemedel kan ge en nedsatt salivkörtelfunktion, vilket är en riskfaktor för karies och andra sjukdomar i munhålan. På 7 slumpmässigt utvalda patienter som alla fick samma medicin mätte man under 5 minuter den så kallade tuggstimulerade saliven. Normal mängd saliv under dessa förhållanden är 1 ml/min och muntorrhet anses föreligga när mängden saliv understiger 0.7 ml/min. Som modell antog man att salivmängden är normalfördelad med väntevärde <span class="math inline">\(\mu\)</span> och standardavvikelse <span class="math inline">\(\sigma\)</span>, där <span class="math inline">\(\sigma\)</span> anses vara 0.5 ml/min. Intressanta frågeställningar är t.ex.:</p>
<ul>
<li>Stöder data vår misstanke att medicinen sänker salivproduktionen?</li>
<li>Om medicinen ger upphov till en genomsnittlig salivproduktion på 0.8 ml/min, hur troligt är det att vi kommer att missa den nedsatta salivproduktionen med vårt test?</li>
<li>Hur många patienter ska vi mäta på om vi vill att testet ska upptäcka en nedsatt salivproduktion på 0.7,ml/min med sannolikheten 0.95?</li>
</ul>
<p>På kursens hemsida hittar ni data i filen <code>saliv.RData</code>. Kortfattade svar till frågorna som ställs i uppgifterna finns i slutet på denna del av handledningen.</p>
</blockquote>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Uppgift 1.1
</div>
</div>
<div class="callout-body-container callout-body">
<p>Först vill man undersöka om data från de 7 patienterna stöder vår misstanke att medicinen sänker salivproduktionen. Ställ upp modell och lämpliga hypoteser.</p>
</div>
</div>
<p><strong>Modell</strong>: <!-- ta bort detta och ange modell här  --></p>
<p><strong>Hypoteser</strong>: <!-- ta bort detta och ange hypoteser här  --></p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Uppgift 1.2
</div>
</div>
<div class="callout-body-container callout-body">
<p>Beräkna medelvärdet av mätningarna.</p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># skriv din R-kod här</span></span></code><button title="Kopiera till Urklipp" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Svar</strong>: <!-- ta bort detta och skriv upp medelvärdet för stickprovet --></p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Uppgift 1.3
</div>
</div>
<div class="callout-body-container callout-body">
<p>Använd rutinen <code>hypotes</code> för att illustrera testets kritiska område då testet utförs på signifikansnivå <span class="math inline">\(\alpha = 0.05\)</span>. Det aktuella kommandot är <code>hypotes(</code><span class="math inline">\(\sigma\)</span>, <span class="math inline">\(n\)</span>, <span class="math inline">\(\mu_0\)</span>, <span class="math inline">\(\alpha\)</span>, <code>H1-riktn)</code>. Med hypoteserna <span class="math inline">\(H_0: \mu = 1\)</span> och <span class="math inline">\(H_1: \mu &lt; 1\)</span> blir kommandot <code>hypotes(0.5, 7, 1, 0.05, '&lt;')</code>. Använd rutinen fast med de hypoteser du har formulerat. (Bortse från de felmeddelanden som eventuellt kommer och titta på figuren.)</p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># skriv din R-kod här</span></span></code><button title="Kopiera till Urklipp" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Uppgift 1.4
</div>
</div>
<div class="callout-body-container callout-body">
<p>Rutinen markerar det kritiska området och anger ett värde <span class="math inline">\(k\)</span> som är gränsen till området. Hur har <span class="math inline">\(k\)</span> beräknats? Ställ upp den matematiska formeln för <span class="math inline">\(k\)</span> och använd den för att själv beräkna <span class="math inline">\(k\)</span>.</p>
</div>
</div>
<p><strong>Ekvation för <span class="math inline">\(k\)</span></strong>: <!-- ta bort detta och skriv uttrycket --></p>
<p><strong>Egen beräkning av <span class="math inline">\(k\)</span></strong>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># skriv din R-kod här</span></span></code><button title="Kopiera till Urklipp" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Uppgift 1.5
</div>
</div>
<div class="callout-body-container callout-body">
<p>Använd ditt beräknade stickprovsmedelvärde för att utföra testet. Vad är din slutsats om nollhypotesen, <span class="math inline">\(H_0\)</span>?</p>
</div>
</div>
<p><strong>Svar:</strong> <!-- ta bort detta och skriv dina slutsatser i enkel text --></p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Uppgift 1.6
</div>
</div>
<div class="callout-body-container callout-body">
<p>Vad är din konkreta tolkning av signifikansnivån <span class="math inline">\(\alpha = 0.05\)</span> i detta exempel?</p>
</div>
</div>
<p><strong>Svar:</strong> <!-- ta bort detta och skriv dina slutsatser i enkel text --></p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Uppgift 1.7
</div>
</div>
<div class="callout-body-container callout-body">
<p>Undersök hur det kritiska område ändras då du ändrar signifikansnivån till <span class="math inline">\(\alpha = 0.01\)</span>. Vad är din slutsats nu?</p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># skriv din R-kod här</span></span></code><button title="Kopiera till Urklipp" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Svar:</strong> <!-- ta bort detta och skriv dina slutsatser i enkel text --></p>
</section>
<section id="testets-styrka-och-styrkefunktion" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Testets styrka och styrkefunktion</h1>
<blockquote class="blockquote">
<p>Antag nu att genomsnittlig salivutsöndring i riskgruppen är 0.8. Då är förstås <span class="math inline">\(H_0: \mu = 1\)</span> falsk och vi vill att vårt test ska upptäcka detta och förkasta denna hypotes till förmån för hypotesen <span class="math inline">\(H_1: \mu &lt; 1\)</span>. Sannolikheten att testet verkligen klarar av detta kallas för testets styrka i punkten 0.8. Använd rutinen <code>hypotes</code> för att illustrera testets styrka i punkten 0.8. Kommandot är nu <code>hypotes(</code><span class="math inline">\(\sigma\)</span>, <span class="math inline">\(n\)</span>, <span class="math inline">\(\mu_0\)</span>, <span class="math inline">\(\alpha\)</span>, H1-riktn, sant <span class="math inline">\(\mu\)</span><code>)</code>, så i detta fall skriver du <code>hypotes(0.5, 7, 1, 0.05, '&lt;', 0.8)</code>.</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hypotes</span>(<span class="fl">0.5</span>, <span class="dv">7</span>, <span class="dv">1</span>, <span class="fl">0.05</span>, <span class="st">'&lt;'</span>, <span class="fl">0.8</span>)</span></code><button title="Kopiera till Urklipp" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Lab3_student_rapport_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" style="width:80.0%"></p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Uppgift 2.1
</div>
</div>
<div class="callout-body-container callout-body">
<p>Rutinen ger dig ytterligare en figur som, förutom signifikansnivån <span class="math inline">\(\alpha\)</span> (felrisk av typ I), även visar <span class="math inline">\(\beta\)</span> (felrisk av typ II). Vad är den konkreta tolkningen av <span class="math inline">\(\beta\)</span> i detta exempel? Hur hänger <span class="math inline">\(\beta\)</span> ihop med testets styrka?</p>
<p>Generellt är testets styrka i punkten <span class="math inline">\(\mu\)</span> sannolikheten att nollhypotesen förkastas om <span class="math inline">\(\mu\)</span> är verklig genomsnittlig salivutsöndring i riskgruppen, d.v.s.</p>
<p><span class="math display">\[
S(\mu)=P(\text{$H_0$ förkastas|$\mu$})
\]</span></p>
<p>Observera att styrkan beror på värdet <span class="math inline">\(\mu\)</span>. I detta exempel gäller att ju mindre <span class="math inline">\(\mu\)</span> är i förhållande till <span class="math inline">\(\mu_0= 1\)</span> desto större är chansen att testet ska upptäcka att <span class="math inline">\(H_0\)</span> inte gäller. Därför är det intressant att studera styrkan som en funktion av <span class="math inline">\(\mu\)</span>, denna funktion betecknas ofta <span class="math inline">\(S(\mu)\)</span>.</p>
<p>Rutinen ritar upp styrkefunktionen, kommandot är om du vill rita upp funktionen och markera ett speciellt <span class="math inline">\(\mu\)</span>-värde. Använd alltså kommandot <code>styrka(0.5, 7, 1, 0.05, '&lt;', 0.8)</code>, vilket ger dig den tidigare figuren plus styrkan som en funktion av <span class="math inline">\(\mu\)</span>.</p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">styrka</span>(<span class="fl">0.5</span>, <span class="dv">7</span>, <span class="dv">1</span>, <span class="fl">0.05</span>, <span class="st">'&lt;'</span>, <span class="fl">0.8</span>)</span></code><button title="Kopiera till Urklipp" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Lab3_student_rapport_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" style="width:80.0%"></p>
</div>
</div>
<!-- ta bort detta och skriv dina slutsatser i enkel text -->
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Uppgift 2.2
</div>
</div>
<div class="callout-body-container callout-body">
<p>Uppskatta utifrån styrkefunktionen hur stor sannolikheten är att vi med vårt test kommer upptäcka att en grupp som bör klassas som muntorra (<span class="math inline">\(\mu= 0.7\)</span>) har en sänkt salivproduktion.</p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># skriv din R-kod här</span></span></code><button title="Kopiera till Urklipp" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Svar:</strong> <!-- ta bort detta och skriv dina slutsatser i enkel text --></p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Uppgift 2.3
</div>
</div>
<div class="callout-body-container callout-body">
<p>Hur många patienter bör vi mäta på om vi med sannolikheten 0.95 verkligen ska upptäcka att muntorra har en sänkt salivproduktion? Tips: Testa med olika värden på <span class="math inline">\(n\)</span> i <code>styrkefkn</code>.</p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># skriv din R-kod här</span></span></code><button title="Kopiera till Urklipp" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Svar:</strong> <!-- ta bort detta och skriv dina slutsatser i enkel text --></p>
<section id="svar-till-exemplet-med-muntorrhet" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="svar-till-exemplet-med-muntorrhet">Svar till exemplet med muntorrhet</h2>
<ol type="1">
<li>Del 1<br>
1.1 <span class="math inline">\(H_0: \mu = 1\)</span>; <span class="math inline">\(H_1: \mu &lt; 1\)</span><br>
1.2 <span class="math inline">\(k=\mu_0 - z_{1-\alpha}\, \frac{\sigma}{\sqrt{n}} = 1-1.6445 \cdot \frac{0.05}{\sqrt{7}}=0.689\)</span><br>
1.5 Eftersom medelvärdet <span class="math inline">\(&lt; 0.689\)</span> förkastas <span class="math inline">\(H_0\)</span> på nivå 0.05<br>
1.6 Det finns en chans på 5% att vi påstår att en person i riskgruppen har en sänkt salivproduktion när den i själva verket är normal 1.7 <span class="math inline">\(H_0\)</span> kan ej förkastas på nivå 0.01</li>
<li>Del 2<br>
2.1 <span class="math inline">\(\beta = P(\text{ej förkasta} H_0|\mu)\)</span>, d.v.s. <span class="math inline">\(\beta\)</span> när det sanna väntevärdet är 0.8 är 1-strykan i punkten 0.8 = 1- S(0.8)<br>
2.2 Styrkan i punkten 0.7, S(0.7), kan enligt figuren uppskattas till 0.48<br>
2.3 Det krävs <span class="math inline">\(n=30\)</span> patienter för att styrkan ska vara 0.95 i punkten 0.7</li>
</ol>
</section>
<section id="några-statistiska-test-med-stickprov" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="några-statistiska-test-med-stickprov">Några statistiska test med stickprov</h2>
<blockquote class="blockquote">
<p>Kortfattade svar till frågorna som ställs i uppgifterna finns i slutet på denna del av handledning. Datamaterialen som används är albumin, bladklorofyll och dammar, vilka du hittar på Canvas.</p>
</blockquote>
</section>
</section>
<section id="test-av-väntevärde-i-en-population-t-test" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Test av väntevärde i en population (t-test)</h1>
<blockquote class="blockquote">
<p>En blandning av blodserum innehåller exakt 42 g albumin per liter. Två laboratorier (A och B) får göra sex bestämningar var av koncentrationen. Vi vill undersöka om det finns någon systematisk avvikelse från det sanna värdet (42 g/l) i var och en av dessa två grupper.</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"data/lab3_mini2_filer/albumin.RData"</span>)</span></code><button title="Kopiera till Urklipp" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Uppgift 3.1
</div>
</div>
<div class="callout-body-container callout-body">
<p>Ange modell för A och B och specificera hypoteser för att testa om det finns en systematisk avvikelse från det sanna värdet i respektive grupp. Ledtråd: det ska vara en tvåsidig mothypotes.</p>
</div>
</div>
<p><strong>Modell för grupp A:</strong> Låt <span class="math inline">\(X\)</span> vara koncentration g albumin per liter i mätningar från laboration A. Väntevärde och varians för <span class="math inline">\(X\)</span> är <span class="math inline">\(\mu_x\)</span> och <span class="math inline">\(\sigma^2_x\)</span>. Antag att mätningar är oberoende och likafördelade. Väntevärdet skattas med stickprovsmedelvärdet <span class="math inline">\(\hat{\mu}_x=\bar{x}\)</span>. Enligt centrala gränsvärdessatsen är <span class="math inline">\(\bar{x} \overset{A}{\sim} N(\mu_x,\frac{\sigma_x}{\sqrt{n_x}})\)</span>.</p>
<p><strong>Hypoteser för grupp A:</strong> <!-- ta bort detta och skriv dina hypoteser--></p>
<p><strong>Modell för grupp B:</strong> Låt <span class="math inline">\(Y\)</span> vara koncentration g albumin per liter i mätningar från laboration B.<!-- ta bort detta och fortsätt skriva din modell, ange antagande--></p>
<p><strong>Hypoteser för grupp B:</strong> <!-- ta bort detta och skriv dina hypoteser--></p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Uppgift 3.2
</div>
</div>
<div class="callout-body-container callout-body">
<p>I R gör man dessa två t-test med nedanstående rutinen <code>t-test</code>. Tolka utskrifterna när du kör kommandot. Hur stora är <span class="math inline">\(p\)</span>-värdena och vad blir slutsatserna för respektive grupp? Vad blir konfidensintervallen för de förväntade koncentrationerna?</p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(AlbuminA, <span class="at">mu=</span><span class="dv">42</span>)</span></code><button title="Kopiera till Urklipp" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  AlbuminA
t = 2.9194, df = 5, p-value = 0.03304
alternative hypothesis: true mean is not equal to 42
95 percent confidence interval:
 42.05974 42.94026
sample estimates:
mean of x 
     42.5 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(AlbuminB, <span class="at">mu=</span><span class="dv">42</span>)</span></code><button title="Kopiera till Urklipp" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  AlbuminB
t = -2.1843, df = 5, p-value = 0.08067
alternative hypothesis: true mean is not equal to 42
95 percent confidence interval:
 35.68716 42.51284
sample estimates:
mean of x 
     39.1 </code></pre>
</div>
</div>
<p><strong>Svar:</strong> <!-- ta bort detta och skriv dina slutsatser i enkel text --></p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Uppgift 3.3
</div>
</div>
<div class="callout-body-container callout-body">
<p>Antag att vi vill undersöka om <strong>laboration B</strong> under- respektive överskattar koncentrationer. I R gör man detta som ett ensidigt test med rutinen <code>t-test</code>.</p>
<p>Tolka utskriften för ensidiga test för laboration B. Vad händer med <span class="math inline">\(p\)</span>-värden och intervall när man går från ensidigt till tvåsidiga alternativ?</p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(AlbuminB, <span class="at">mu=</span><span class="dv">42</span>, <span class="at">alternative=</span><span class="st">"less"</span>)</span></code><button title="Kopiera till Urklipp" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  AlbuminB
t = -2.1843, df = 5, p-value = 0.04034
alternative hypothesis: true mean is less than 42
95 percent confidence interval:
     -Inf 41.77529
sample estimates:
mean of x 
     39.1 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(AlbuminB, <span class="at">mu=</span><span class="dv">42</span>, <span class="at">alternative=</span><span class="st">"greater"</span>)</span></code><button title="Kopiera till Urklipp" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  AlbuminB
t = -2.1843, df = 5, p-value = 0.9597
alternative hypothesis: true mean is greater than 42
95 percent confidence interval:
 36.42471      Inf
sample estimates:
mean of x 
     39.1 </code></pre>
</div>
</div>
<p><strong>Svar:</strong> <!-- ta bort detta och skriv dina slutsatser i enkel text --></p>
</section>
<section id="jämförelse-av-väntevärden-i-två-populationer-t-test-vid-två-oberoende-stickprov" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Jämförelse av väntevärden i två populationer (t-test vid två oberoende stickprov)</h1>
<blockquote class="blockquote">
<p>Alger i fick växa under ljusa respektive mörka förhållanden och därefter mättes klorofyllhalt.</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"data/lab3_mini2_filer/alger.RData"</span>)</span></code><button title="Kopiera till Urklipp" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Uppgift 4.1
</div>
</div>
<div class="callout-body-container callout-body">
<p>Gör en grafisk beskrivning av skillnaderna. Vad visar låd-diagrammet (boxplotten)?</p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(Alger<span class="sc">$</span>Klorofyll <span class="sc">~</span> Alger<span class="sc">$</span>Grupp)</span></code><button title="Kopiera till Urklipp" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Lab3_student_rapport_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Svar:</strong><!-- ta bort detta och skriv dina slutsatser i enkel text --></p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Uppgift 4.2
</div>
</div>
<div class="callout-body-container callout-body">
<p>Sätt upp modell och hypoteser, och undersök med ett t-test om det finns skillnader i förväntad klorofyllhalt mellan de två grupperna.</p>
<p>Detta kan man göra genom att lägga till gruppvariabeln i rutinen <code>t.test</code>. Tolka utskriften.</p>
</div>
</div>
<p><strong>Modell:</strong> Låt <span class="math inline">\(X\)</span> vara tillväxt hos alger i mörka förhållanden med väntevärde <span class="math inline">\(\mu_x\)</span> och varians <span class="math inline">\(\sigma^2_x\)</span>, och <span class="math inline">\(Y\)</span> vara tillväxt hos alger i ljusa förhållanden med väntevärde <span class="math inline">\(\mu_y\)</span> och varians <span class="math inline">\(\sigma^2_y\)</span>. Väntevärden skattas med stickprovsmedelvärden <span class="math inline">\(\hat{\mu_x}=\bar{x}\)</span> och <span class="math inline">\(\hat{\mu_y}=\bar{y}\)</span>. Enligt centrala gränsvärdessatsen kommer skattningen av respektive väntevärde vara approximativt normalfördelad, d.v.s. <span class="math inline">\(\bar{x} \overset{A}{\sim} N(\mu_x,\frac{\sigma_x}{\sqrt{n_x}})\)</span> och <span class="math inline">\(\bar{y} \overset{A}{\sim} N(\mu_y,\frac{\sigma_y}{\sqrt{n_y}})\)</span>.</p>
<p><strong>Hypoteser:</strong> <span class="math inline">\(H_0: \mu_x = \mu_y\)</span> mot <span class="math inline">\(H_1: \mu_x \neq \mu_y\)</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Alger<span class="sc">$</span>Klorofyll <span class="sc">~</span> Alger<span class="sc">$</span>Grupp)</span></code><button title="Kopiera till Urklipp" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  Alger$Klorofyll by Alger$Grupp
t = -3.2089, df = 9.0652, p-value = 0.01058
alternative hypothesis: true difference in means between group Ljus and group Mörker is not equal to 0
95 percent confidence interval:
 -11.219229  -1.947438
sample estimates:
  mean in group Ljus mean in group Mörker 
            13.10000             19.68333 </code></pre>
</div>
</div>
<p><strong>Svar:</strong> <!-- ta bort detta och skriv dina slutsatser i enkel text --></p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Uppgift 4.3
</div>
</div>
<div class="callout-body-container callout-body">
<p>Om vi inte säger något annat förutsätter rutinen <code>t.test</code> att varianserna i de två grupperna, d.v.s. <span class="math inline">\(\sigma^2_x\)</span> och <span class="math inline">\(\sigma^2_y\)</span> är <strong>olika</strong> och kompenserar för det. Om vi vet (eller antar) att varianserna är lika, kan vi utnyttja det för att få högre frihetsgrader eftersom det är en parameter färre att skatta.</p>
<p>Undersök om varianserna är lika med ett så kallat <span class="math inline">\(\chi^2\)</span>-test. Det gör man i R genom rutinen <code>var.test</code>. Tolka utskriften!</p>
</div>
</div>
<p><strong>Hypoteser</strong>: <span class="math inline">\(H_0: \sigma^2_x = \sigma^2_y\)</span> mot <span class="math inline">\(H_1: \sigma^2_x \neq \sigma^2_y\)</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">var.test</span>(Alger<span class="sc">$</span>Klorofyll <span class="sc">~</span> Alger<span class="sc">$</span>Grupp)</span></code><button title="Kopiera till Urklipp" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    F test to compare two variances

data:  Alger$Klorofyll by Alger$Grupp
F = 0.51386, num df = 5, denom df = 5, p-value = 0.4825
alternative hypothesis: true ratio of variances is not equal to 1
95 percent confidence interval:
 0.07190457 3.67222210
sample estimates:
ratio of variances 
         0.5138575 </code></pre>
</div>
</div>
<p><strong>Svar:</strong> <!-- ta bort detta och skriv dina slutsatser i enkel text --></p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Uppgift 4.4
</div>
</div>
<div class="callout-body-container callout-body">
<p>Gör om t-testet där du antar att varianser är lika genom att lägga till <code>var.equal=TRUE</code> i R-rutien. Vad blir dina slutsatser nu?</p>
</div>
</div>
<p><strong>Antagande</strong>: <span class="math inline">\(\sigma^2=\sigma^2_x = \sigma^2_y\)</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Alger<span class="sc">$</span>Klorofyll <span class="sc">~</span> Alger<span class="sc">$</span>Grupp, <span class="at">var.equal=</span><span class="cn">TRUE</span>)</span></code><button title="Kopiera till Urklipp" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  Alger$Klorofyll by Alger$Grupp
t = -3.2089, df = 10, p-value = 0.009349
alternative hypothesis: true difference in means between group Ljus and group Mörker is not equal to 0
95 percent confidence interval:
 -11.154519  -2.012148
sample estimates:
  mean in group Ljus mean in group Mörker 
            13.10000             19.68333 </code></pre>
</div>
</div>
<p><strong>Svar:</strong> <!-- ta bort detta och skriv dina slutsatser i enkel text --></p>
</section>
<section id="test-vid-matchade-data-stickprov-i-par" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Test vid matchade data (stickprov i par)</h1>
<blockquote class="blockquote">
<p>Det har gjorts mätningar av kvävebelastning under vår respektive sommar på ett antal dammar. Om man vill jämföra kvävebelastningen mellan de två årstiderna är en rimlig modell “stickprov i par”.</p>
</blockquote>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"data/lab3_mini2_filer/dammar.RData"</span>)</span></code><button title="Kopiera till Urklipp" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Modell:</strong> Låt <span class="math inline">\(D\)</span> vara skillnaden i mätning under vår och sommare för en damm, med väntevärde <span class="math inline">\(\mu\)</span> och varians <span class="math inline">\(\sigma^2\)</span>. Vi skapar ett stickprov <span class="math inline">\((d_1,...,d_n)\)</span> för skillnader i mätvärden. Väntevärdet skattas med stickprovsmedelvärdet, <span class="math inline">\(\hat{\mu}=\bar{d}\)</span>. Enligt centrala gränsvärdessatsen är <span class="math inline">\(\bar{d} \overset{A}{\sim} N(\mu,\frac{\sigma}{\sqrt{n}})\)</span>.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Uppgift 5.1
</div>
</div>
<div class="callout-body-container callout-body">
<p>Finns det en skillnad i väntevärden mellan vår och sommar?</p>
<p>Vi testar det med följande <strong>hypoteser:</strong> <span class="math inline">\(H_0: \mu = 0\)</span> mot <span class="math inline">\(H_1: \mu \neq 0\)</span></p>
<p>Detta är ett vanligt test och man behöver inte räkna ut ett nytt stickprov. För att tala om för <code>t.test</code> att data är matchade i par lägger man till paired=TRUE som argument.</p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Dammar<span class="sc">$</span>N_belast_V, Dammar<span class="sc">$</span>N_belast_S, <span class="at">paired=</span><span class="cn">TRUE</span>)</span></code><button title="Kopiera till Urklipp" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  Dammar$N_belast_V and Dammar$N_belast_S
t = 1.2189, df = 7, p-value = 0.2624
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
 -19.49477  60.97227
sample estimates:
mean difference 
       20.73875 </code></pre>
</div>
</div>
<p><strong>Svar</strong>: <!-- ta bort detta och skriv dina slutsatser i enkel text --></p>
<section id="svar-till-några-av-denna-sektions-frågor" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="svar-till-några-av-denna-sektions-frågor">Svar till några av denna sektions frågor:</h2>
<ol type="1">
<li>Svar<br>
3.2 A: p-värde<span class="math inline">\(=0.033\)</span>; B: p-värde<span class="math inline">\(=0.081\)</span>; Vi kan påvisa en skillnad för A men inte för B. 95% konfidensintervall: A: <span class="math inline">\((42,06,\,42.94)\)</span>; B: <span class="math inline">\((35.69,\,42.51)\)</span><br>
4.3 Varianserna är inte olika (p-värde<span class="math inline">\(=0.48\)</span>)<br>
4.4 t-test: p-värde<span class="math inline">\(=0.009\)</span>; Vi kan påvisa en skillnad i klorofyll.<br>
5.1 p-värde<span class="math inline">\(=0.262\)</span> Vi kan inte påvisa någon skillnad</li>
</ol>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Kopieras!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Kopieras!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>